spring.application.name=reume-builder


# Datasource configuration
#spring.datasource.username=postgres
#spring.datasource.password=8439563366
#spring.datasource.url=jdbc:postgresql://localhost:5432/resume_builder
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always



management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=resume_builer-01

# emial configuration

 spring.mail.host=smtp-relay.brevo.com
 spring.mail.port=587
 spring.mail.username=a85b1e001@smtp-brevo.com
 spring.mail.password=bskuGqit0fmS8C9
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=sidraw2006@gmail.com

#application
 app.base.url=http://localhost:8080
